title: Learn Linear Algebra
author: Chris Snow
execute:
  execute_notebooks: cache
  kernel_manager_class: jupyter_client.manager.KernelManager
  kernel_name_map:
    sagemath: sagemath-10.6
exclude_patterns: ['README.md']
html:
  extra_path: ['_static']